#! /bin/bash/


echo "




               ▄█▀─▄▄▄▄▄▄▄─▀█▄
               ▀█████████████▀
               ────█▄███▄█
               ─────█████
               ─────█▀█▀█
            
               St0ner-Metal
 

"
mpv --no-video http://79.120.77.11:8002/stonermetal




