#!/data/data/com.termux/files/usr/bin/bash

#                     pip install --upgrade youtube-dl

#  apt-get install ffmpeg
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
bla='\e[1;97m'
sub='\e[4m'
fos='\e[5m'

fin='\033[0m'
########     Fin Colores ##############----
 #                                                       /dev/null 2>&1 &
#k44="$(sh /xg/0r/.betas/i/pm-am2)"
###### Fecha  &  Hora   ######
rdias="$(date +%A)"
mes="$(date +%B)"
diaf="$(date +%e)"
ttime="$(date +'%I:%M')"
ye="$(date +%Y)"

#########   Fechas/hora   ############
#diasem="$(date +%A)"
#diasem="$(sh /xg/0r/.betas/i/dias)"
mes="$(date +%B)"
diafech="$(date +%e)"
timme="$(date +'%I:%M')"
#timme="$(date +'%I:%M'|toilet -f future)"
ye="$(date +%Y)"
######################################
###### fin fecha ##############




#c00l="$(sh /xg/0r/.betas/i/color)"
#------------------------------------------------------------
bban1 () {
clear
echo ""
echo ""
toilet -f pagga descargas
toilet -f future --metal youtube.mp3
echo ""
echo ""

}









selecc () {
clear

                                                                               
 echo "
░░░░░░░░░░░░░░░░░░░$roj▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄$fin░░░░░░░░░░░░░
██░░██░░░░░░░░░░░$roj▄█░░░░░░████░░████████▄$fin░░░░░░░░░░░
██▄▄██░░░░░░░░░░░$roj████░░██████░░█████████$fin░░ █▀▀▄ █░░ 
▀████▀░████░█░░█░$roj████░░█░██░█░▄▄░█░░▄▄██$fin▀▀ █░░█ █░░ 
░░██░░░█░░█░█▄▄█░$roj████░░█░░░░█░▀▀░█░░▄▄██$fin░░ ▀▀▀░ ▀▀▀ 
░░██░░░████░████░$roj▀███▄▄█▄▄▄▄█▄▄▄▄█▄▄▄▄█▀$fin░░░░░░░░░░░
░░░░░░░░░░░░░░░░░░░$roj▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀$fin░░░░░░░░░░░░░
$cy0
               ᗪ乇丂匚卂尺G卂丂 $fin
  Version::: 
               ▀▀█▀▀ ─ ░█▀▀▀ ─ ░█─── ─ 
               ─░█──   ░█▀▀▀   ░█───  
               ─░█── ▄ ░█▄▄▄ ▄ ░█▄▄█ ▄ $fin

           爪卩3 
───────────────────┤$roj m $fin 


      ᐯ丨ᗪ乇ㄖ丂 
───────────────────┤$roj v $fin

  ㄥ丨丂ㄒ卂.爪卩3 
───────────────────┤$roj l $fin 

░Ｓａｌｉｒ░ [$roj x$fin ]"                                                                                 

echo -n "$ama ========================$fin? "
read RESP
case $RESP in
	m ) sleep 1; clear; mmpp;;
 up ) actu; selecc;;
	l ) sleep 1; clear; list;;
	v ) sleep 1; clear; vids;;
	x ) clear; exx;;
	* ) sleep 1; echo "
 Opción incorrecta";sleep 1; bban1; selecc;;
esac
}



mmpp () {
echo "

$ama


▒█▀▀▄ █▀▀ █▀▀ █▀▀ █▀▀█ █▀▀█ █▀▀▀ █▀▀█ █▀▀ 
▒█░▒█ █▀▀ ▀▀█ █░░ █▄▄█ █▄▄▀ █░▀█ █▄▄█ ▀▀█ 
▒█▄▄▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀░░▀ ▀░▀▀ ▀▀▀▀ ▀░░▀ ▀▀▀ 
$fin
░ ▒█▀▄▀█ █▀▀█ █▀▀█ 
▄ ▒█▒█▒█ █░░█ ░░▀▄ 
█ ▒█░░▒█ █▀▀▀ █▄▄█






"
echo -n "      ┌─[$roj░Ｐｅｇａ░Ｌｉｎｋ░$fin
      │
      └──┤"




read dees
echo "$ama"

echo "#############################################"
echo "#############################################"
echo "#############################################"
echo "#############################################$ama
Ｐｏｓｉｂｌｅ　Ｔｉｔｕｌｏ　ｄｅ　ａｒｃｈｉｖｏ．ｍｐ３$fin"
w3m $dees >> ll
cat ll|sed -n '46p;47p;48p'
rm -f ll
echo "

"
read -p " ☠ GЦΛЯDΛЯ ᄃӨMӨ::::" kof
#read -p " Guardar como: " kof
#n0m=$(zenity --title="☠ GЦΛЯDΛЯ ᄃӨMӨ ☠"  --entry --width 600)

#rutt=$(zenity  --file-selection --title="Selecciona Caperta para Guardar:::" --directory)


#mkdir .mux
cd /storage/emulated/0/Download/1/yt
rutt="$(pwd)"
mkdir x1
cd x1
#clear
#echo ""
echo "

 $roj
___  ____ ____ ____ ____ ____ ____ ____ _  _ ___  ____    
|  \ |___ [__  |    |__| |__/ | __ |__| |\ | |  \ |  |    
|__/ |___ ___] |___ |  | |  \ |__] |  | | \| |__/ |__| ...
                                                          $fin
"
#toilet -f emboss2 --metal --filter border Descargando..#
echo "
"

youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 $dees
#youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 mp3 --yes-playlist $dees
echo ""


mv *.mp3 "$kof.mp3"
mv *.mp3 $rutt
cd ..
rm -fr x1
date +'%I:%M'|toilet -f future >> lol
t1="$(sed -n 1p lol)"
t2="$(sed -n 2p lol)"
t3="$(sed -n 3p lol)"
rm -f lol
echo "  
$ama


       Ξｌ░Λｒｃｈｉｖｏ░Ｍｐ３░ｓｅ░Ｄｅｓｃａｒｇｏ░ａ：
              $fin [$roj $rutt $fin] "
echo "



"

}



vids () {
echo "
$roj
▒█▀▀▄ █▀▀ █▀▀ █▀▀ █▀▀█ █▀▀█ █▀▀▀ █▀▀█ █▀▀ 
▒█░▒█ █▀▀ ▀▀█ █░░ █▄▄█ █▄▄▀ █░▀█ █▄▄█ ▀▀█ 
▒█▄▄▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀░░▀ ▀░▀▀ ▀▀▀▀ ▀░░▀ ▀▀▀  $fin

█▀▀▄ █▀▀ 
█░░█ █▀▀ 
▀▀▀░ ▀▀▀ $roj

▒█░░▒█ ░▀░ █▀▀▄ █▀▀ █▀▀█ █▀▀ 
░▒█▒█░ ▀█▀ █░░█ █▀▀ █░░█ ▀▀█ 
░░▀▄▀░ ▀▀▀ ▀▀▀░ ▀▀▀ ▀▀▀▀ ▀▀▀ 

$fin


"
echo -n "      ┌─[$ama░Ｐｅｇａ░Ｌｉｎｋ░$fin
      │
      └─┤"    
read deesz
echo ""
sleep 1s
echo "###################################################"
echo "###################################################"
echo "###################################################"
echo "###################################################"
#read -p " Guardar como: " kof
#n0m=$(zenity --title="☠ GЦΛЯDΛЯ ᄃӨMӨ ☠"  --entry --width 600)

#rutt=$(zenity  --file-selection --title="Selecciona Caperta para Guardar:::" --directory)
cd /storage/emulated/0/Download/1/yt/v
rutt="$(pwd)"
#cd
#mkdir .mux
#cd .mux
#clear
echo " $ama
___  ____ ____ ____ ____ ____ ____ ____ _  _ ___  ____    
|  \ |___ [__  |    |__| |__/ | __ |__| |\ | |  \ |  |    
|__/ |___ ___] |___ |  | |  \ |__] |  | | \| |__/ |__|$fin ...
                                                           




"
#toilet -f emboss2 --metal --filter border Descargando..#
cd $rutt
youtube-dl $deesz
#youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 mp3 --yes-playlist $dees
echo ""
date +'%I:%M'|toilet -f future >> lol
t1="$(sed -n 1p lol)"
t2="$(sed -n 2p lol)"
t3="$(sed -n 3p lol)"
rm -f lol
#mv *.mp3 "$n0m.mp3"
#mv *.mp3 $rutt
#cd ..
#rm -r .mux
echo " $ama   Σᄂ ΛЯᄃΉIVӨ DΣ VIDΣӨ 
    ƧΣ DΣƧᄃΛЯGӨ ΣП : $fin  [$roj $rutt $fin] "
echo ""

echo "


"
echo ""




}




list () {
echo "
$ama
___  ____ ____ ____ ____ ____ ____ ____ ____ 
|  \ |___ [__  |    |__| |__/ | __ |__| [__  
|__/ |___ ___] |___ |  | |  \ |__] |  | ___] 
                                                $fin
___  ____                                    
|  \ |___                                    
|__/ |___                                    
      
$roj
  _     _     _                     
 | |   (_)___| |_ __ _              
 | |   | / __| __/ _° |             
 | |___| \__ \ || (_| |             
 |_____|_|___/\__\__,_|       _____ 
               _ __ ___  _ __|___ / 
              | °_ ° _ \| *_ \ |_ \ 
             _| | | | | | |_) |__) |
            (_)_| |_| |_| .__/____/ 
                        |_|         
$fin


"
echo -n "      ┌─[$ama░Ｐｅｇａ░Ｌｉｎｋ░$fin
      │
      └┤"
read deesx
echo ""

echo "#################################"
echo "#################################"
echo "#################################"
echo "#################################"
read -p " Guardar CARPETA como: " n0m
#n0m=$(zenity --title="☠ GЦΛЯDΛЯ ᄃӨMӨ ☠"  --entry --width 600)

#rutt=$(zenity  --file-selection --title="Selecciona/Crea Caperta para Guardar Lista.mp3:::" --directory)
cd /storage/emulated/0/Download/1/yt
rutt="$(pwd)"
#cd
#mkdir .mux
#cd .mux
clear
echo ""
echo "






"
toilet -f emboss2 --metal --filter border :::Descargando:::Lista:::.#
echo "
"
cd $rutt
mkdir $n0m
cd $n0m
#youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 mp3  $deesx
youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 mp3 --yes-playlist $deesx
echo ""
rutt="$(pwd)"
#mv *.mp3 "$n0m.mp3"
#mv *.mp3 $rutt
#cd ..
#rm -r .mux
echo " $ama Ｌｏｓ　Ａｒｃｈｉｖｏｓ　Ｍｐ３　
ｓｅ　Ｄｅｓｃａｒｇａｒｏｎ　ｅｎ: $fin  [$roj $rutt $fin] "
echo ""
echo ""
echo ""
echo ""




}

selecc
