#!/data/data/com.termux/files/usr/bin/bash
############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'
gri='\e[2m'
#----------------
fin='\033[0m'
#----------------

#bannc0l="$(sh /xg/0r/.betas/i/colorbanner)"
########     Fin Colores ##############----

#------------------------------------------------------------
#########   Fechas/hora   ############
diasem="$(date +%A)"
mes="$(date +%b)"
#diaf="$(date +%e)"
ttime="$(date +'%I:%M')"

tt3="$(date +%M)"
#timwe="$(date +'%I::%M')"
ye="$(date +%Y)"
######################################
#-------------------------------------------

########################### ip/red ####################
#ipp="$(curl ifconfig.co)"  > /dev/null 2>&1
#ip="$(ip route show|grep ' src ' |cut -d' ' -f12)"
#ant3=`netstat -r | grep "default" | awk {'print $8'}`
#nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################



inici0 () {
	echo ""
clear
echo "

 Respaldo
    termux
       .tar


"
cd

  cp /data/data/com.termux/files/usr/etc/bash.bashrc /data/data/com.termux/files/home
  cp /data/data/com.termux/files/usr/etc/nginx/nginx-conf /data/data/com.termux/files/home



  tar -cvf resp-termx_$mes$ye.tar bash.bashrc nginx-conf 99


mv *.tar  /data/data/com.termux/files/home/storage/downloads 

cd /data/data/com.termux/files/home/storage/downloads
echo "

"
ls *.tar   
echo "

"
echo "
$roj
     R e s p a l d o

        C o m p l e t a d o...
$fin"
 # /data/data/com.termux/files/home

} 









#n0mb=$(zenity --title="☠ Ｕｓｕａｒｉｏ ☠" --text ":::Escribe tu Nombre de Usuario en GitHub:::" --entry --width 100) > /dev/null 2>&1

#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub:::::::")  > /dev/null 2>&1
#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub::::::: "--directory)  > /dev/null 2>&1

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################
# > /dev/null 2>&1
#

###################################
inici0
