#!/data/data/com.termux/files/usr/bin/bash
ko=$(date +%H)
#ali () {

############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
#ver0='\033[1;32m'
ve2='\033[92m'
#ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'

cy='\033[36m'
#cy0='\033[1;36m'
##---------------
sub='\e[4m'
#fos='\e[5m'
gri='\e[2m'
#----------------
fin='\033[01;37m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /data/data/com.termux/files/home/99/0/az
touch /data/data/com.termux/files/home/99/0/az
echo "#!/data/data/com.termux/files/usr/bin/bash" >> /data/data/com.termux/files/home/99/0/az


#echo "az='\033[34m'" >> /data/data/com.termux/files/home/99/0/az

#echo "clear" >> /data/data/com.termux/files/home/99/0/az
#echo "azz=$(echo '\e[34m')" >> /data/data/com.termux/files/home/99/0/az

#shs#        green, red, blue, white, yellow, cyan, magenta  black.


######## Madrugada
echo "alias 00='sh /data/data/com.termux/files/home/99/ban/b/banpentester'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 01='sh /data/data/com.termux/files/home/99/ban/b/noche2'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 02='sh /data/data/com.termux/files/home/99/ban/b/banpentester'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 03='sh /data/data/com.termux/files/home/99/ban/b/noche'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 04='sh /data/data/com.termux/files/home/99/ban/b/banpentester'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 05='sh /data/data/com.termux/files/home/99/ban/b/noche2'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 06='sh /data/data/com.termux/files/home/99/ban/b/ban-crann'" >> /data/data/com.termux/files/home/99/0/az

########## Mañana
echo "alias 07='sh /data/data/com.termux/files/home/99/ban/b/mañana'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 08='sh /data/data/com.termux/files/home/99/ban/b/mañana'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 09='sh /data/data/com.termux/files/home/99/ban/b/mañana'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 10='sh /data/data/com.termux/files/home/99/ban/b/mañana'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 11='sh /data/data/com.termux/files/home/99/ban/b/mañana'" >> /data/data/com.termux/files/home/99/0/az

######### Tarde
echo "alias 12='sh /data/data/com.termux/files/home/99/ban/b/tarde'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 13='sh /data/data/com.termux/files/home/99/ban/b/tarde'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 14='sh /data/data/com.termux/files/home/99/ban/b/ban-crann'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 15='sh /data/data/com.termux/files/home/99/ban/b/tarde'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 16='sh /data/data/com.termux/files/home/99/ban/b/ban-crann'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 17='sh /data/data/com.termux/files/home/99/ban/b/ban-crann'" >> /data/data/com.termux/files/home/99/0/az
######### Crepusculo

echo "alias 18='sh /data/data/com.termux/files/home/99/ban/b/crepusculo'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 19='sh /data/data/com.termux/files/home/99/ban/b/crepusculo'" >> /data/data/com.termux/files/home/99/0/az

#########  noche 

echo "alias 20='sh /data/data/com.termux/files/home/99/ban/b/banpentester'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 21='sh /data/data/com.termux/files/home/99/ban/b/noche2'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 22='sh /data/data/com.termux/files/home/99/ban/b/ban-crann'" >> /data/data/com.termux/files/home/99/0/az
echo "alias 23='sh /data/data/com.termux/files/home/99/ban/b/noche'" >> /data/data/com.termux/files/home/99/0/az


#alias llo='echo -e "$az NOCHE" '


echo $ko >> /data/data/com.termux/files/home/99/0/az
###### >>
sh /data/data/com.termux/files/home/99/0/az
###### >>
rm -f /data/data/com.termux/files/home/99/0/az

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali











