#!/data/data/com.termux/files/usr/bin/bash
############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'


cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'
gri='\e[2m'
#----------------

fin='\033[01;37m'

##### Hora en Toilet ###############
# date +'%I:%M'|toilet -f future >> lol
date +'%I:%M'|toilet -f future >> lol
t1="$(sed -n 1p lol)"
t2="$(sed -n 2p lol)"
t3="$(sed -n 3p lol)"
rm -f lol
####################################
##### Hora en Toilet ###############
# date +'%I:%M'|toilet -f future >> lol
date +%P|toilet -f future >> loll
tt1="$(sed -n 1p loll)"
tt2="$(sed -n 2p loll)"
tt3="$(sed -n 3p loll)"
rm -f loll
#############################

#########   Fechas/hora   ############
diasem="$(date +%A)"
#diasem="$(sh /xg/0r/.betas/i/dias)"
#mes="$(date +%B)"
diafech="$(date +%e)"
timme="$(date +'%I:%M')"
#timme="$(date +'%I:%M'|toilet -f future)"
ye="$(date +%Y)"
######################################

#ipp="$(curl ifconfig.co)"  > /dev/null 2>&1
ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
ant3="$(ip route show|grep ' dev ' |cut -d' ' -f3)"
lika2="$(uname -o)"
mex="$(sh /data/data/com.termux/files/home/99/ban/mes)"
diax="$(sh /data/data/com.termux/files/home/99/ban/dias)"
c00l="$(sh /data/data/com.termux/files/home/99/ban/colorxx2)"

clx="$(sh /data/data/com.termux/files/home/99/ban/colorxx)"
cxx="$(sh /data/data/com.termux/files/home/99/ban/color22)"
echo -n "$c00l"
cat /data/data/com.termux/files/home/99/ban/b/noche-1
echo "$fin
  ╔$clx$diax$fin  
  ╚═══════════════════╣$diafech$fin
                      ╚═══╣ $ro2$mex$fin 🔹 $cy0$ye$fin
📡$ama$ant3$fin 🔻 🏠 $roj$ip$fin ╚╚═══════════════════════╗
                                      
 $clx$t1$fin $tt1$fin     
 $clx$t2$fin $tt2$fin $cxx 
 $clx$t3$fin▪$tt3$fin
"
