#!/data/data/com.termux/files/usr/bin/bash
############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'
gri='\e[2m'
#----------------

fin='\033[01;37m'
#########   Fechas/hora   ############
diasem="$(date +%A)"
#diasem="$(sh /xg/0r/.betas/i/dias)"
#mes="$(date +%B)"
diafech="$(date +%e)"
timme="$(date +'%I:%M')"
#timme="$(date +'%I:%M'|toilet -f future)"
ye="$(date +%Y)"
######################################

#ipp="$(curl ifconfig.co)"  > /dev/null 2>&1
ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
ant3="$(ip route show|grep ' dev ' |cut -d' ' -f3)"
lika2="$(uname -o)"
mex="$(sh /data/data/com.termux/files/home/99/ban/mes)"
diax="$(sh /data/data/com.termux/files/home/99/ban/dias)"
colxx="$(sh /data/data/com.termux/files/home/99/ban/colorxx2)"


echo "  ㄒｅｒｍｕｘ 乇ｘｐｅｒｔ ㄥａｕｎｃｈｅｒ

::$colxx$diax$fin::
  └──┤\033[1;33m$diafech$fin•$ro2$mex$fin•$cy0$ye

$colxx     6666666666666
$colxx    6666666666666666  📱$fin$lika2
$colxx   666666666666666666 
$colxx   666666666666666666 
$colxx   666666  666  66666 📡$ama$ant3$fin
$colxx   66666   666   6666 
$colxx   666666666 66666666 
$colxx   66666666 * 6666666 🏠$roj $ip $fin
$colxx  66666666666666666666 
    66666666666666666 
     **|*  *|* * *|* 
$fin"


