#! /bin/bash/
ko=$(date +%H)
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
##---------------


########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /data/data/com.termux/files/home/99/0/aliaz
touch /data/data/com.termux/files/home/99/0/aliaz
echo '#! /bin/bash/' >> /data/data/com.termux/files/home/99/0/aliaz


#echo "az='\033[34m'" >> /data/data/com.termux/files/home/99/0/aliaz

#echo "clear" >> /data/data/com.termux/files/home/99/0/aliaz
#echo "azz=$(echo '\e[34m')" >> /data/data/com.termux/files/home/99/0/aliaz

echo "alias 00='echo "🌓🌜"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 01='echo "🌌 🌙"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 02='echo "🌛"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 03='echo "🌜😴"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 04='echo "🌙"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 05='echo "🌒"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 06='echo "🌙 🌅"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 07='echo "🌄"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 08='echo "🌅🌞"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 09='echo "🌞"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 10='echo "⛅"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 11='echo "🌞"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 12='echo "🌝"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 13='echo "🌞😎"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 14='echo "🌞"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 15='echo "🌞🔥"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 16='echo "⛅🌞"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 17='echo "⛅☀"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 18='echo "⛅"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 19='echo "⛅🌇"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 20='echo "🌆🌒"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 21='echo "⭐🌃"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 22='echo "🌃✯🌜"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 23='echo "🌙"'" >> /data/data/com.termux/files/home/99/0/aliaz


#alias llo='echo -e "$az NOCHE" '


echo $ko >> /data/data/com.termux/files/home/99/0/aliaz
sh /data/data/com.termux/files/home/99/0/aliaz
rm -f /data/data/com.termux/files/home/99/0/aliaz

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali











