#! /bin/bash/
############  Colores  #################
rojff='\033[1;31m'
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'
rojsub='\e[1;4;91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
amas='\033[1;4;33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'
neg='\e[1m'
pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'
gri='\e[2m'
#----------------
fin='\033[01;37m'
#----------------


#------------------------------------------------------------
##################
#-------------------------------------------
# xcc="$(date +'%M%S')"
cxx="$(sh /data/data/com.termux/files/home/99/ban/color22)"

########################### ip/red ####################
#ipp="$(curl ifconfig.co)"  > /dev/null 2>&1
#ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#ant3=`netstat -r | grep "default" | awk {'print $8'}`
#nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################



inici0 () {
#	echo ""
#clear
ppw="$(pwd)"
echo "   ┌──────┤📂$roj$ppw $fin"
ls *.mp3
echo "
               
      ░░█▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
      ██▀▀▀██▀▀▀▀▀▀██▀▀▀██
      █▒▒▒▒▒█▒▀▀▀▀▒█▒▒▒▒▒█
      █▒▒▒▒▒█▒████▒█▒▒▒▒▒█
      ██▄▄▄██▄▄▄▄▄▄██▄▄▄██
$cxx

       ▒█▀▄▀█ █▀▀█ ▒█░░▒█ 
       ▒█▒█▒█ █░░█ ░▒█▒█░ 
       ▒█░░▒█ █▀▀▀ ░░▀▄▀░
       
       "
echo " $ama
    尺eproduciendo 卂udio .Ｍ卩3 $fin
 
 🎧  🎶  🎵🎧  🎶  🎵 🎶 🎶
"

} 









#n0mb=$(zenity --title="☠ Ｕｓｕａｒｉｏ ☠" --text ":::Escribe tu Nombre de Usuario en GitHub:::" --entry --width 100) > /dev/null 2>&1

#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub:::::::")  > /dev/null 2>&1
#ppsx=$(zenity  --file-selection --title="Selecciona un Archivo Para Subir a GitHub::::::: "--directory)  > /dev/null 2>&1

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################
# > /dev/null 2>&1
#
###################################

###################################
inici0