#! /bin/bash/
ko=$(date +%H)
#ali () {
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\033[01;37m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /data/data/com.termux/files/home/99/0/aliaz
touch /data/data/com.termux/files/home/99/0/aliaz
echo '#! /bin/bash/' >> /data/data/com.termux/files/home/99/0/aliaz


#echo "az='\033[34m'" >> /data/data/com.termux/files/home/99/0/aliaz

#echo "clear" >> /data/data/com.termux/files/home/99/0/aliaz
#echo "azz=$(echo '\e[34m')" >> /data/data/com.termux/files/home/99/0/aliaz

#
#        green, red, blue, white, yellow, cyan, magenta  black.

echo "alias 00='echo "cyan"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 01='echo "magenta"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 02='echo "black"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 03='echo "cyan"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 04='echo "magenta"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 05='echo "cyan"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 06='echo "black"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 07='echo "white"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 08='echo "blue"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 09='echo "green"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 10='echo "black"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 11='echo "green"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 12='echo "yellow"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 13='echo "red"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 14='echo "yellow"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 15='echo "red"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 16='echo "yellow"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 17='echo "yellow"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 18='echo "red"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 19='echo "blue"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 20='echo "magenta"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 21='echo "cyan"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 22='echo "magenta"'" >> /data/data/com.termux/files/home/99/0/aliaz
echo "alias 23='echo "blue"'" >> /data/data/com.termux/files/home/99/0/aliaz


#alias llo='echo -e "$az NOCHE" '


echo $ko >> /data/data/com.termux/files/home/99/0/aliaz
sh /data/data/com.termux/files/home/99/0/aliaz
rm -f /data/data/com.termux/files/home/99/0/aliaz

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali











